### ISSUE TITLE
Program is no longer maintained

### ISSUE THREAD

**Issue by rg3** [rg3/slackroll#1]
Recently, I moved away from Slackware. I'm still using it in a couple of boxes here and there, but it's no longer present in my main system. This means the program will eventually bitrot as I'm no longer using it. In any case, Slackware doesn't change much over time. It should be safe to continue using slackroll at least until the mirror structure changes, or until Python 3 becomes the default version.

**Comment by abchk1234** [comment]
I just discovered slackroll after someone [posted](https://www.linuxquestions.org/questions/slackware-14/contemplating-the-future-of-slackware-4175535608/page5.html#post5327594) on the forums; seems like an interesting tool so far :)

**Comment by Gunbird** [comment]
That's too bad. Slackroll is still the best packet manager for slackware in my opinion.

**Comment by ryanpcmcquen** [comment]
What OS did you move to?

**Comment by rg3** [comment]
I'm currently running Fedora.
