### ISSUE TITLE
It is not clear how you would process any .new files after running "slackroll batch upgrade".

### ISSUE THREAD

**Issue by Richard-Cranium** [rg3/slackroll#16]
After running "slackroll batch upgrade", among the other messages telling me "Ignoring nonexistent [X].new and keeping [X]" messages, there may be messages stating "Keeping both [X].new and [X] for manual review".

Is there a way to trigger such a manual review?  Or must I read the messages and do it by hand?

**Comment by rg3** [comment]
> Is there a way to trigger such a manual review? Or must I read the 
> messages and do it by hand?

I didn't code the "batch" operation, but I'm guessing it's an informative message so you know the list of files and can review them later manually.

Without using "batch", slackroll will take the chance to peek into the local packages database taking into account only those packages that have changed (which can be a small list) and let you review the list of .new files.

When using "batch" the list would have to be reviewed "after the fact", which is slightly more complicated. If slackroll had a separate operation to do it, it would have to review the contents of each installed package to find cases of .new files, but it would be missing information about .new files from packages that were removed, for example, so it's an imperfect solution.

I prefer the current approach of letting the user know the full and proper list and let them act accordingly. My two cents.

**Comment by Richard-Cranium** [comment]
> I didn't code the "batch" operation, but I'm guessing it's an informative message so you know the list of files and can review them later manually.

Well, the batch operation won't force you to say "Y" to every time the .new file matches what was already there without the .new extension.  If there were a configuration property to tell slackroll to do assume that I'm okay with dropping the .new file if the matching not-.new file is the exactly the same, I would set that in a heartbeat and never use 'batch' again.

OTOH, given that you don't use Slackware at all now, is there someone else I should bother with these issues?  Please don't get me wrong, it's wonderful that you still respond, but I'd rather not annoy you to support something that you created in the past to support your needs but really don't need any more.

**Comment by aclemons** [comment]
I wrote the original batch implementation (I also maintain slackroll on slackbuilds.org). I wrote it mostly for automating patches with something like ansible. I don't need the new files since my configurations live in code and I as the admin will have looked at the incoming patches and updated any configs necessary before rolling the patch to all the servers.

I'm happy to add something to slackroll to help out solving your problem. I don't think I quite know yet exactly what feature you need.

**Comment by aclemons** [comment]
Ok, I think I see what you are after. Basically, you do not want to be prompted for unchanged files (package installation moves the .new file directly to the target) when running a normal interactive `slackroll upgrade`. This saves you hitting `X` for `(X) Review next pair` for each of the new files. But if this did not happen, you still want the prompt to choose what to do (move, diff, next, remove).

Is this correct?

**Comment by rg3** [comment]
I could be an interesting feature. When both files exist, slackroll would first check if they are binary identical. If they are, slackroll would remove the .new file and skip prompting about the pair.

**Comment by rg3** [comment]
> OTOH, given that you don't use Slackware at all now, is there someone else I should bother with these issues? Please don't get me wrong, it's wonderful that you still respond, but I'd rather not annoy you to support something that you created in the past to support your needs but really don't need any more.

This is still the official repo. As you can see, @aclemons has been helping.

**Comment by Richard-Cranium** [comment]
> Ok, I think I see what you are after. Basically, you do not want to be prompted for unchanged files (package installation moves the .new file directly to the target) when running a normal interactive `slackroll upgrade`. This saves you hitting `X` for `(X) Review next pair` for each of the new files. But if this did not happen, you still want the prompt to choose what to do (move, diff, next, remove).
> 
> Is this correct?

That is exactly what I would want.

**Comment by Gunbird** [comment]
I would also be very interested to see this new behavior of .new files implemented in slackroll.

I would not like to see the total amount of time I spent hitting the "x" key after a slackroll upgrade because that would be depressing ;-)

Thanks for your work

**Comment by Gunbird** [comment]
Is there any plan to implement this feature request ?

Also are you going to release a new version with the glibc-solibs renaming supported ?

Regards

**Comment by spillner** [comment]
I addressed this (along with other improvements) in https://github.com/rg3/slackroll/pull/22 . I'm still not sure who ever had a use case for the original behavior (being prompted whenever a package provides a .new file, but it's identical to what you already have installed), but we could add a --prompt-all-new flag if someone misses it.
