### ISSUE TITLE
Dependabot alerts

### ISSUE THREAD

**Issue by rg3** [rg3/slackroll#50]
For some months now I've been receiving emails from GitHub about "Known security vulnerabilities detected" in the "slackroll/slackroll" project. For me, this is the only project generating this kind of alerts.

The culprit appears to be a dependency on "py" version "<= 1.11.0", which appears to be the vulnerable software, defined in "poetry.lock". Could this be fixed to stop receiving these emails? Thanks.

**Comment by aclemons** [comment]
It's a transitive dependency of pytest, but there is no version of pytest which still supports 2.7 which does not pull it in. slackroll itself doesn't have any dependencies outside of python, so I've disabled dependabot alerts for this repo. The notifications should stop now.
