### ISSUE TITLE
After upgrading from v48 to v51 I get "OSError: [Errno 18] Invalid cross-device link" on slackware current and stable

### ISSUE THREAD

**Issue by Gunbird** [rg3/slackroll#52]
Hi,

I just upgraded to slackroll v51 on several boxes running slackwaez64-current and stable and on both versions just by running `slackoll update`

 I get the error : 
`Traceback (most recent call last):`
`  File "/usr/sbin/slackroll", line 2164, in <module>`
`    persistent_list = load_persistent_db(slackroll_persistentlist_filename)`
`  File "/usr/sbin/slackroll", line 1787, in load_persistent_db`
`    os.rename(temp_file, filename)`
`OSError: [Errno 18] Invalid cross-device link`

**Comment by Gunbird** [comment]
My /tmp filesystem is on a separate LV.

Replacing `os.rename` by : 
```
shutil.copy(temp_file,filename)
os.remove(temp_file)
```

seems to fix the problem.

**Comment by rg3** [comment]
There's also `shutil.move`, which calls `os.rename` if optimal and falls back to something like that.

**Comment by Gunbird** [comment]
I confirm that in my case `shutil.move` also works.

But it is explained in the documentation that : 

> If the destination is on the current filesystem, then [os.rename()](https://docs.python.org/2/library/os.html#os.rename) is used

https://docs.python.org/2/library/shutil.html#shutil.move
https://docs.python.org/3/library/shutil.html#shutil.move

And this is with python2 and python3 so there may be cases where it may not work for some people.

**Comment by aclemons** [comment]
I've released a new version now with this fix. It should also be on slackbuilds.org after this weekend's update
