### ISSUE TITLE
Small error in handle_dotnew_files_removal

### ISSUE THREAD

**Issue by leoctrl** [rg3/slackroll#55]
Hi Andrew,
first of all, thanks for maintaining slackroll, IMHO it's the best third party Slackware Package Manager available.
That said, I guess I spotted a small error in handle_dotnew_files_removal, where it says

    if slackroll_batch_mode:
        handle_dotnew_files_removal_batch(dotnew_files)
    else:
        handle_dotnew_files_removal_interactive(dotnew_files)

it should be instead

    if slackroll_batch_mode:
        handle_dotnew_files_removal_batch(existing)
    else:
        handle_dotnew_files_removal_interactive(existing)

Thanks

**Comment by aclemons** [comment]
Thanks for raising this. I've pushed the fix. Looks like I broke this in b43104893cc672332a82c97dc4e3153fcadc6ebf.

I'll make a release and make sure it goes out in next week's SBo updates too.
